okta_token            = "your-okta-api-token"
okta_org              = "https://your-okta-organization-url"
azure_subscription_id = "your-azure-subscription-id"
azure_tenant_id       = "your-azure-tenant-id"
azure_client_id       = "your-azure-client-id"
azure_client_secret   = "your-azure-client-secret"
azure_location        = "your-azure-region"
